# -*- coding: utf-8 -*-
"""Stemmer and lemmatize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SRdzjVbrKTEhMKnUDae5jlaKjDzDJSXu
"""

article_text="Just what is agility in the context of software engineering work? Ivar Jacobs"

import re
import nltk
from nltk.tokenize import word_tokenize

article_text = article_text.lower()
article_text

clean_text = re.sub('[^a-zA-Z]', ' ', article_text)
clean_text = re.sub('\s+', ' ', clean_text)
clean_text

import nltk
nltk.download('punkt')

sentence_list = nltk.sent_tokenize(article_text)
sentence_list

tokens=word_tokenize(clean_text)

tokens

import nltk
nltk.download('stopwords')

stopwords = nltk.corpus.stopwords.words('english')
impword=[]
word_frequencies = {}
for word in tokens:
    if word not in stopwords:
       impword.append(word)
       if word not in word_frequencies:
          word_frequencies[word] = 1
       else:
           word_frequencies[word]+= 1
impword

word_frequencies

from collections import Counter

dictionary=Counter(word_frequencies)

from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

porter = PorterStemmer()
lancaster=LancasterStemmer()
print("Porter Stemmer")
print(porter.stem("cats"))
print(porter.stem("trouble"))
print(porter.stem("troubling"))
print(porter.stem("troubled"))
print("Lancaster Stemmer")
print(lancaster.stem("cats"))
print(lancaster.stem("trouble"))
print(lancaster.stem("troubling"))
print(lancaster.stem("troubled"))

word_list = ["friend", "friendship", "friends", "friendships","stabil","destabilize","misun"]
print("{0:20}{1:20}{2:20}".format("Word","Porter Stemmer","lancaster Stemmer"))
for word in word_list:
    print("{0:20}{1:20}{2:20}".format(word,porter.stem(word),lancaster.stem(word)))

stem_sentence=[]
for word in tokens:
    stem_sentence.append(porter.stem(word))
    stem_sentence.append(" ")
stem_sentence

from nltk.stem import WordNetLemmatizer
lem1 = WordNetLemmatizer()

import nltk
nltk.download('all')

print("{0:20}{1:20}".format("Word","Lemma"))
for word in impword:
    print ("{0:20}{1:20}".format(word,lem1.lemmatize(word)))