# -*- coding: utf-8 -*-
"""text_summerization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HVcgb_X7yXdq_VCJaeXVipQrot2lkLsX
"""

article_text="Just what is agility in the context of software engineering work? Ivar Jacobs"

import re
import nltk
from nltk.tokenize import word_tokenize

article_text = article_text.lower()
article_text

clean_text = re.sub('[^a-zA-Z]', ' ', article_text)
clean_text = re.sub('\s+', ' ', clean_text)
clean_text

import nltk
nltk.download('punkt')

sentence_list = nltk.sent_tokenize(article_text)
sentence_list

tokens=word_tokenize(article_text)

tokens

import nltk
nltk.download("stopwords")

stopwords = nltk.corpus.stopwords.words('english')
word_frequencies = {}
for word in tokens:
 if word not in stopwords:
  if word not in word_frequencies:
    word_frequencies[word] = 1

word_frequencies

import nltk
from nltk.corpus import brown
from nltk import FreqDist
news_text = brown.words(categories='news')
fdist = FreqDist([w.lower() for w in news_text])

import nltk
nltk.download('all')

word_freq=FreqDist(word_frequencies)

word_freq.plot(30,title='freqplot')

from collections import Counter

dictionary=Counter(word_freq)

dictionary=Counter(word_freq)

import matplotlib.pyplot as plt
from wordcloud import WordCloud

cloud=WordCloud(max_font_size=80,colormap='hsv').generate_from_frequencies(dictionary)

plt.figure(figsize=(16,13))
plt.imshow(cloud,interpolation='bilinear')
plt.axis('off')
plt.show()